/****** Object:  Table [dbo].[PupilInformation]    Script Date: 16-04-2022 19:31:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SchoolResults](
	[UniqueId] [int] IDENTITY(1,1) NOT NULL,
	[PupilUniqueId] [int] NOT NULL,
	[CITO group1first READING] [nvarchar](max) NULL,
	[DLE group1first READING] [nvarchar](max) NULL,
	[CITOgroup1second READING] [nvarchar](max) NULL,
	[DLE group1second READING] [nvarchar](max) NULL,
	[CITO group2first READING] [nvarchar](max) NULL,
	[DLE group2first  READING] [nvarchar](max) NULL,
	[CITOgroup2second READING] [nvarchar](max) NULL,
	[DLE group2second READING] [nvarchar](max) NULL,
	[CITO group3first READING] [nvarchar](max) NULL,
	[DLE group3first READING] [nvarchar](max) NULL,
	[CITOgroup3second READING] [nvarchar](max) NULL,
	[DLE group3second READING] [nvarchar](max) NULL,
	[CITO group4first READING] [nvarchar](max) NULL,
	[DLE group4first READING] [nvarchar](max) NULL,
	[CITOgroup4second READING] [nvarchar](max) NULL,
	[DLE group4second READING] [nvarchar](max) NULL,
	[CITO group5first READING] [nvarchar](max) NULL,
	[DLE group5first READING] [nvarchar](max) NULL,
	[CITOgroup5second READING] [nvarchar](max) NULL,
	[DLE group5second READING] [nvarchar](max) NULL,
	[CITO group6first READING] [nvarchar](max) NULL,
	[DLE group6first READING] [nvarchar](max) NULL,
	[CITOgroup6second READING] [nvarchar](max) NULL,
	[DLE group6second READING] [nvarchar](max) NULL,
	[CITO group7first READING] [nvarchar](max) NULL,
	[DLE group7first READING] [nvarchar](max) NULL,
	[CITOgroup7second READING] [nvarchar](max) NULL,
	[DLE group7second READING] [nvarchar](max) NULL,
	[CITO group8first READING] [nvarchar](max) NULL,
	[DLE group8first READING] [nvarchar](max) NULL,
	[CITOgroup8second READING] [nvarchar](max) NULL,
	[DLE group8second READING] [nvarchar](max) NULL,
	[Summary cito or dle results READING] [nvarchar](max) NULL,
	[CITO group1first WRITING] [nvarchar](max) NULL,
	[DLE group1first WRITING] [nvarchar](max) NULL,
	[CITOgroup1second WRITING] [nvarchar](max) NULL,
	[DLE group1second WRITING] [nvarchar](max) NULL,
	[CITO group2first WRITING] [nvarchar](max) NULL,
	[DLE group2first  WRITING] [nvarchar](max) NULL,
	[CITOgroup2second WRITING] [nvarchar](max) NULL,
	[DLE group2second WRITING] [nvarchar](max) NULL,
	[CITO group3first WRITING] [nvarchar](max) NULL,
	[DLE group3first WRITING] [nvarchar](max) NULL,
	[CITOgroup3second WRITING] [nvarchar](max) NULL,
	[DLE group3second WRITING] [nvarchar](max) NULL,
	[CITO group4first WRITING] [nvarchar](max) NULL,
	[DLE group4first WRITING] [nvarchar](max) NULL,
	[CITOgroup4second WRITING] [nvarchar](max) NULL,
	[DLE group4second WRITING] [nvarchar](max) NULL,
	[CITO group5first WRITING] [nvarchar](max) NULL,
	[DLE group5first WRITING] [nvarchar](max) NULL,
	[CITOgroup5second WRITING] [nvarchar](max) NULL,
	[DLE group5second WRITING] [nvarchar](max) NULL,
	[CITO group6first WRITING] [nvarchar](max) NULL,
	[DLE group6first WRITING] [nvarchar](max) NULL,
	[CITOgroup6second WRITING] [nvarchar](max) NULL,
	[DLE group6second WRITING] [nvarchar](max) NULL,
	[CITO group7first WRITING] [nvarchar](max) NULL,
	[DLE group7first WRITING] [nvarchar](max) NULL,
	[CITOgroup7second WRITING] [nvarchar](max) NULL,
	[DLE group7second WRITING] [nvarchar](max) NULL,
	[CITO group8first WRITING] [nvarchar](max) NULL,
	[DLE group8first WRITING] [nvarchar](max) NULL,
	[CITOgroup8second WRITING] [nvarchar](max) NULL,
	[DLE group8second WRITING] [nvarchar](max) NULL,
	[Summary cito or dle results WRITING] [nvarchar](max) NULL,
	[CITO group1first ARITHMETIC] [nvarchar](max) NULL,
	[DLE group1first ARITHMETIC] [nvarchar](max) NULL,
	[CITOgroup1second ARITHMETIC] [nvarchar](max) NULL,
	[DLE group1second ARITHMETIC] [nvarchar](max) NULL,
	[CITO group2first ARITHMETIC] [nvarchar](max) NULL,
	[DLE group2first  ARITHMETIC] [nvarchar](max) NULL,
	[CITOgroup2second ARITHMETIC] [nvarchar](max) NULL,
	[DLE group2second ARITHMETIC] [nvarchar](max) NULL,
	[CITO group3first ARITHMETIC] [nvarchar](max) NULL,
	[DLE group3first ARITHMETIC] [nvarchar](max) NULL,
	[CITOgroup3second ARITHMETIC] [nvarchar](max) NULL,
	[DLE group3second ARITHMETIC] [nvarchar](max) NULL,
	[CITO group4first ARITHMETIC] [nvarchar](max) NULL,
	[DLE group4first ARITHMETIC] [nvarchar](max) NULL,
	[CITOgroup4second ARITHMETIC] [nvarchar](max) NULL,
	[DLE group4second ARITHMETIC] [nvarchar](max) NULL,
	[CITO group5first ARITHMETIC] [nvarchar](max) NULL,
	[DLE group5first ARITHMETIC] [nvarchar](max) NULL,
	[CITOgroup5second ARITHMETIC] [nvarchar](max) NULL,
	[DLE group5second ARITHMETIC] [nvarchar](max) NULL,
	[CITO group6first ARITHMETIC] [nvarchar](max) NULL,
	[DLE group6first ARITHMETIC] [nvarchar](max) NULL,
	[CITOgroup6second ARITHMETIC] [nvarchar](max) NULL,
	[DLE group6second ARITHMETIC] [nvarchar](max) NULL,
	[CITO group7first ARITHMETIC] [nvarchar](max) NULL,
	[DLE group7first ARITHMETIC] [nvarchar](max) NULL,
	[CITOgroup7second ARITHMETIC] [nvarchar](max) NULL,
	[DLE group7second ARITHMETIC] [nvarchar](max) NULL,
	[CITO group8first ARITHMETIC] [nvarchar](max) NULL,
	[DLE group8first ARITHMETIC] [nvarchar](max) NULL,
	[CITOgroup8second ARITHMETIC] [nvarchar](max) NULL,
	[DLE group8second ARITHMETIC] [nvarchar](max) NULL,
	[summary cito or dle results ARITHMETIC] [nvarchar](max) NULL,
	[Integrative summary writing reading arithmetic] [nvarchar](max) NULL,
	[School advice previoius school] [nvarchar](max) NULL,
	[Any particulars] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[UniqueId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


