namespace IPMO_PracticeManagementWebApp.Model
{
    public class SchoolResults
    {
        public int PupilUniqueId { get; set; }
        public string CITO_group1first_READING { get; set; }
        public string DLE_group1first_READING { get; set; }
        public string CITO_group1second_READING { get; set; }
        public string DLE_group1second_READING { get; set; }
        public string CITO_group2first_READING { get; set; }
        public string DLE_group2first_READING { get; set; }
        public string CITO_group2second_READING { get; set; }
        public string DLE_group2second_READING { get; set; }
        public string CITO_group3first_READING { get; set; }
        public string DLE_group3first_READING { get; set; }
        public string CITO_group3second_READING { get; set; }
        public string DLE_group3second_READING { get; set; }
        public string CITO_group4first_READING { get; set; }
        public string DLE_group4first_READING { get; set; }
        public string CITO_group4second_READING { get; set; }
        public string DLE_group4second_READING { get; set; }
        public string CITO_group5first_READING { get; set; }
        public string DLE_group5first_READING { get; set; }
        public string CITO_group5second_READING { get; set; }
        public string DLE_group5second_READING { get; set; }
        public string CITO_group6first_READING { get; set; }
        public string DLE_group6first_READING { get; set; }
        public string CITO_group6second_READING { get; set; }
        public string DLE_group6second_READING { get; set; }
        public string CITO_group7first_READING { get; set; }
        public string DLE_group7first_READING { get; set; }
        public string CITO_group7second_READING { get; set; }
        public string DLE_group7second_READING { get; set; }
        public string CITO_group8first_READING { get; set; }
        public string DLE_group8first_READING { get; set; }
        public string CITO_group8second_READING { get; set; }
        public string DLE_group8second_READING { get; set; }
        public string Summary_cito_or_dle_results_READING { get; set; }
        public string CITO_group1first_WRITING { get; set; }
        public string DLE_group1first_WRITING { get; set; }
        public string CITO_group1second_WRITING { get; set; }
        public string DLE_group1second_WRITING { get; set; }
        public string CITO_group2first_WRITING { get; set; }
        public string DLE_group2first_WRITING { get; set; }
        public string CITO_group2second_WRITING { get; set; }
        public string DLE_group2second_WRITING { get; set; }
        public string CITO_group3first_WRITING { get; set; }
        public string DLE_group3first_WRITING { get; set; }
        public string CITO_group3second_WRITING { get; set; }
        public string DLE_group3second_WRITING { get; set; }
        public string CITO_group4first_WRITING { get; set; }
        public string DLE_group4first_WRITING { get; set; }
        public string CITO_group4second_WRITING { get; set; }
        public string DLE_group4second_WRITING { get; set; }
        public string CITO_group5first_WRITING { get; set; }
        public string DLE_group5first_WRITING { get; set; }
        public string CITO_group5second_WRITING { get; set; }
        public string DLE_group5second_WRITING { get; set; }
        public string CITO_group6first_WRITING { get; set; }
        public string DLE_group6first_WRITING { get; set; }
        public string CITO_group6second_WRITING { get; set; }
        public string DLE_group6second_WRITING { get; set; }
        public string CITO_group7first_WRITING { get; set; }
        public string DLE_group7first_WRITING { get; set; }
        public string CITO_group7second_WRITING { get; set; }
        public string DLE_group7second_WRITING { get; set; }
        public string CITO_group8first_WRITING { get; set; }
        public string DLE_group8first_WRITING { get; set; }
        public string CITO_group8second_WRITING { get; set; }
        public string DLE_group8second_WRITING { get; set; }
        public string Summary_cito_or_dle_results_WRITING { get; set; }
        public string CITO_group1first_ARITHMETIC { get; set; }
        public string DLE_group1first_ARITHMETIC { get; set; }
        public string CITO_group1second_ARITHMETIC { get; set; }
        public string DLE_group1second_ARITHMETIC { get; set; }
        public string CITO_group2first_ARITHMETIC { get; set; }
        public string DLE_group2first_ARITHMETIC { get; set; }
        public string CITO_group2second_ARITHMETIC { get; set; }
        public string DLE_group2second_ARITHMETIC { get; set; }
        public string CITO_group3first_ARITHMETIC { get; set; }
        public string DLE_group3first_ARITHMETIC { get; set; }
        public string CITO_group3second_ARITHMETIC { get; set; }
        public string DLE_group3second_ARITHMETIC { get; set; }
        public string CITO_group4first_ARITHMETIC { get; set; }
        public string DLE_group4first_ARITHMETIC { get; set; }
        public string CITO_group4second_ARITHMETIC { get; set; }
        public string DLE_group4second_ARITHMETIC { get; set; }
        public string CITO_group5first_ARITHMETIC { get; set; }
        public string DLE_group5first_ARITHMETIC { get; set; }
        public string CITO_group5second_ARITHMETIC { get; set; }
        public string DLE_group5second_ARITHMETIC { get; set; }
        public string CITO_group6first_ARITHMETIC { get; set; }
        public string DLE_group6first_ARITHMETIC { get; set; }
        public string CITO_group6second_ARITHMETIC { get; set; }
        public string DLE_group6second_ARITHMETIC { get; set; }
        public string CITO_group7first_ARITHMETIC { get; set; }
        public string DLE_group7first_ARITHMETIC { get; set; }
        public string CITO_group7second_ARITHMETIC { get; set; }
        public string DLE_group7second_ARITHMETIC { get; set; }
        public string CITO_group8first_ARITHMETIC { get; set; }
        public string DLE_group8first_ARITHMETIC { get; set; }
        public string CITO_group8second_ARITHMETIC { get; set; }
        public string DLE_group8second_ARITHMETIC { get; set; }
        public string Summary_cito_or_dle_results_ARITHMETIC { get; set; }
        public string Integrative_summary_writing_reading_arithmetic { get; set; }
        public string School_advice_previous_school { get; set; }
        public string Any_particulars { get; set; }

    }
}